[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
error-support = { path = "../support/error" }
log = "0.4"
remote_settings = { path = "../remote_settings" }
serde = { version = "1", features=["derive"] }
serde_json = "1"
thiserror = "2"
url = "2"
viaduct = { path = "../viaduct" }
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }

[dev-dependencies]
expect-test = "1.4"
mockito = { version = "0.31", default-features = false}
viaduct-dev = { path = "../support/viaduct-dev"}

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666", features=["build"]}
