[package]
name = "places"
edition = "2021"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[features]
default = []

[dependencies]
sync15 = { path = "../sync15" }
serde = "1"
serde_derive = "1"
serde_json = "1"
parking_lot = "0.5"
log = "0.4"
lazy_static = "1.4"
url = { version = "2.1", features = ["serde"] }
percent-encoding = "2.1"
caseless = "0.2"
sql-support = { path = "../support/sql" }
types = { path = "../support/types" }
bitflags = "1.2"
idna = "0.2"
memchr = "2.3"
dogear = "0.4"
interrupt-support = { path = "../support/interrupt" }
error-support = { path = "../support/error" }
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"]}
thiserror = "1.0"
anyhow = "1.0"
uniffi = "^0.17"
uniffi_macros = "^0.17"

[dependencies.rusqlite]
version = "0.27.0"
features = ["functions", "window", "bundled"]

[dev-dependencies]
pretty_assertions = "0.6"
tempfile = "3.1"
env_logger = {version = "0.7", default-features = false}

[build-dependencies]
uniffi_build = { version = "^0.17", features=["builtin-bindgen"] }
