[package]
name = "places"
edition = "2021"
version = "0.1.0"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[features]
default = []

[dependencies]
sync15 = { path = "../sync15" }
serde = "1"
serde_derive = "1"
serde_json = "1"
parking_lot = "0.12"
lazy_static = "1.4"
url = { version = "2.1", features = ["serde"] }
percent-encoding = "2.1"
icu_casemap = "2"
rusqlite = { version = "0.37.0", features = ["functions", "window", "bundled", "unlock_notify"] }
sql-support = { path = "../support/sql" }
types = { path = "../support/types" }
bitflags = "1.2"
idna = "1.0.3"
memchr = "2.3"
dogear = "0.5"
interrupt-support = { path = "../support/interrupt" }
error-support = { path = "../support/error" }
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"]}
thiserror = "2"
anyhow = "1.0"
uniffi = { version = "0.31" }

[dev-dependencies]
error-support = { path = "../support/error", features = ["testing"] }
tempfile = "3.1"
sql-support = { path = "../support/sql" }

[build-dependencies]
uniffi = { version = "0.31", features=["build"]}
