[package]
name = "places"
edition = "2018"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
license = "MPL-2.0"

[features]
log_query_plans = ["sql-support/log_query_plans"]
reqwest = ["sync15/reqwest"]
default = []

[dependencies]
sync15 = { path = "../sync15" }
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"
log = "0.4"
lazy_static = "1.1.0"
url = "1.7.1"
failure = "0.1.3"
caseless = "0.2.1"
sql-support = { path = "../support/sql" }
url_serde = "0.2.0"
ffi-support = { path = "../support/ffi" }
bitflags = "1.0.4"
idna = "0.1.5"
memchr = "2.1.3"
prost = "0.5.0"
prost-derive = "0.5.0"
bytes = "0.4.11"
dogear = "0.2.2"
interrupt = { path = "../support/interrupt" }

[dependencies.rusqlite]
version = "0.17.0"
features = ["functions", "bundled"]

[dev-dependencies]
more-asserts = "0.2.1"
env_logger = "0.5.13"
find-places-db = "0.1.0"
clap = "2.32.0"
structopt = "0.2.14"
tempfile = "3.0.4"
rand = "0.5.5"
fxa-client = { path = "../fxa-client" }
criterion = "0.2.9"
tempdir = "0.3.7"
cli-support = { path = "../support/cli" }
pretty_assertions = "0.6.1"
force-viaduct-reqwest = { path = "../support/force-viaduct-reqwest" }
ctrlc = "3.1.1"

[build-dependencies]
prost-build = "0.5.0"

# While we don't have a replacement for termion on Windows yet (and thus
# our example doesn't work on Windows), it does get further in the compilation
# such that "cargo test" etc shows errors in our code rather than in termion.
[target.'cfg(not(windows))'.dev-dependencies]
termion = "1.5.1"

[[bench]]
name = "match_impl"
harness = false

[[bench]]
name = "search"
harness = false