[package]
name = "places"
edition = "2021"
version = "0.1.0"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[features]
default = []

[dependencies]
# TODO: we've enabled the "standalone-sync" feature - see the description
# of this feature in sync15's Cargo.toml for what we should do instead.
sync15 = { path = "../sync15", features=["standalone-sync"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
parking_lot = "0.12"
log = "0.4"
lazy_static = "1.4"
url = { version = "2.5", features = ["serde"] }
percent-encoding = "2.1"
caseless = "0.2"
rusqlite = { workspace = true, features = ["functions", "window", "bundled", "unlock_notify"] }
sql-support = { path = "../support/sql" }
types = { path = "../support/types" }
bitflags = "1.2"
idna = "0.5"
memchr = "2.3"
dogear = "0.5"
interrupt-support = { path = "../support/interrupt" }
error-support = { path = "../support/error" }
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"]}
thiserror = "1.0"
anyhow = "1.0"
uniffi = { workspace = true }

[dev-dependencies]
tempfile = "3.1"
env_logger = {version = "0.10", default-features = false}
sql-support = { path = "../support/sql" }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
