[bindings.kotlin]
# Typically there'd be no `.uniffi` tail, but without it we see obscure
# kotlin errors about being unable to resolve which `rustCall` to use.
package_name = "mozilla.appservices.places.uniffi"

[bindings.swift]
ffi_module_name = "MozillaRustComponents"
ffi_module_filename = "placesFFI"
