[package]
name = "webext-storage-ffi"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[lib]
name = "webext_storage_ffi"
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4.0"
log = "0.4"
ffi-support = "0.4"
serde_json = "1"

[dependencies.webext-storage]
path = ".."
