[package]
name = "sync_manager"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
autofill = { path = "../autofill" }
sync15 = { path = "../sync15" }
places = { path = "../places" }
logins = { path = "../logins" }
tabs = { path = "../tabs" }
thiserror = "1.0"
anyhow = "1.0"
lazy_static = "1.4"
log = "0.4"
sql-support = { path = "../support/sql" }
url = "2.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
parking_lot = ">=0.11,<=0.12"
interrupt-support = { path = "../support/interrupt" }
uniffi = "^0.18"
uniffi_macros = "^0.18"

[build-dependencies]
uniffi_build = { version = "^0.18", features=["builtin-bindgen"] }
