[bindings.kotlin]
package_name = "mozilla.appservices.syncmanager"
cdylib_name = "megazord"

[bindings.swift]
ffi_module_name = "MozillaRustComponents"
ffi_module_filename = "syncmanagerFFI"
generate_module_map = false
