[package]
name = "remerge"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
failure = { version = "0.1.6" }
url = "2.1.0"
serde_json = "1.0.41"
log = "0.4.8"
semver = { version = "0.9.0", features = ["serde"] }
lazy_static = "1.4.0"
index_vec = "0.1.0"

# it's not clear if we should actually use these deps (they're fine and not
# uncommon or anything, but we could avoid them at the cost of slightly more
# code).
matches = "0.1.8"
num-traits = "0.2.8"
