[package]
name = "example-places-utils"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
edition = "2018"
publish = false

[[example]]
name = "places-utils"
path = "src/places-utils.rs"

[dev-dependencies]
places = { path = "../../components/places" }
sync-guid = { path = "../../components/support/guid" }
types = { path = "../../components/support/types" }
sync15 = { path = "../../components/sync15" }
viaduct-reqwest = { path = "../../components/support/viaduct-reqwest" }
interrupt-support = { path = "../../components/support/interrupt" }
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
url = "2.2"
cli-support = { path = "../cli-support" }
structopt = "0.3"
fxa-client = { path = "../../components/fxa-client" }
tempdir = "0.3"
find-places-db = "0.2"
anyhow = "1.0"
ctrlc = "3.2.1"
