[package]
name = "example-places-utils"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
edition = "2021"
publish = false

[[example]]
name = "places-utils"
path = "src/places-utils.rs"

[dev-dependencies]
places = { path = "../../components/places" }
sync-guid = { path = "../../components/support/guid" }
types = { path = "../../components/support/types" }
error-support = { path = "../../components/support/error" }
interrupt-support = { path = "../../components/support/interrupt" }
nss = { path = "../../components/support/rc_crypto/nss" }
sql-support = { path = "../../components/support/sql", features = ["debug-tools"] }
sync15 = { path = "../../components/sync15" }
viaduct = { path = "../../components/viaduct"}
viaduct-hyper = { path = "../../components/support/viaduct-hyper" }
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
url = "2"
cli-support = { path = "../cli-support" }
clap = { version = "4.2", default-features = false, features = ["std", "derive"] }
fxa-client = { path = "../../components/fxa-client" }
tempfile = "3"
anyhow = "1.0"
