[package]
name = "restmail-client"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
thiserror = "2"
viaduct = { path = "../../viaduct" }
error-support = { path = "../error" }
serde_json = "1"
url = "2.2"
