[package]
name = "push-crypto"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
ece = "0.1"
failure = "0.1.5"
failure_derive = "0.1.5"
base64 = "0.10"
openssl = "0.10"
lazy_static = "1.2"
hkdf = "0.7"
sha2 = "0.8"
serde_json="1.0"
log="0.4"

ffi-support = { path = "../../support/ffi" }

push-errors = {path = "../error"}

[features]
# default = ["openssl"]
# openssl = ["ece-crypto-openssl"]
