[general]
# Directories to search for templates, relative to the crate root.
dirs = [ "src/backends/kotlin/templates", "src/backends/swift/templates" ]

[[syntax]]
name = "kt"

[[syntax]]
name = "swift"
