[package]
name = "nimbus-fml"
version = "0.1.0"
edition = "2018"
authors = ["Nimbus SDK Engineering"]
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
anyhow = "1.0.44"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.29"
serde_yaml = "0.8.21"
askama = "0.10.5"
textwrap = "0.14.2"
heck = "0.3.3"
