[package]
name = "autofill"
edition = "2018"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-support = { path = "../support/error" }
interrupt-support = { path = "../support/interrupt" }
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
sql-support = { path = "../support/sql" }
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"] }
sync15-traits = {path = "../support/sync15-traits"}
thiserror = "1.0"
types = { path = "../support/types" }
url = { version = "2.1", features = ["serde"] }

[dependencies.rusqlite]
version = "0.24.1"
features = ["functions", "bundled", "serde_json", "unlock_notify"]

[dev-dependencies]
env_logger = { version = "0.8", default-features = false }
libsqlite3-sys = "0.20.1"

[build-dependencies]
nss_build_common = { path = "../support/rc_crypto/nss/nss_build_common" }
