[package]
name = "webext-storage"
edition = "2021"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
exclude = ["/android"]

[features]
default = []

[dependencies]
anyhow = "1.0"
error-support = { path = "../support/error" }
thiserror = "1.0"
ffi-support = "0.4"
interrupt-support = { path = "../support/interrupt" }
lazy_static = "1.4"
log = "0.4"
parking_lot = ">=0.11,<=0.12"
rusqlite = { version = "0.33.0", features = ["functions", "bundled", "serde_json", "unlock_notify"] }
serde = "1"
serde_json = "1"
serde_derive = "1"
sql-support = { path = "../support/sql" }
sync15 = {path = "../../components/sync15", features=["sync-engine"]}
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"] }
uniffi = { version = "0.28.2" }
url = { version = "2.1", features = ["serde"] }

[dev-dependencies]
env_logger = { version = "0.10", default-features = false }
tempfile = "3"
sql-support = { path = "../support/sql" }
# We add the perserve_order feature to guarantee ordering of the keys in our
# JSON objects as they get serialized/deserialized.
serde_json = { version = "1", features = ["preserve_order"] }

[build-dependencies]
uniffi = { version = "0.28.2", features=["build"]}

# Temp hack for uniffi 0.28 generated code, will not be necessary after next uniffi update.
[lints.clippy]
empty-line-after-doc-comments = "allow"
