[package]
name = "webext-storage"
edition = "2018"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
license = "MPL-2.0"

[dependencies]
error-support = { path = "../support/error" }
failure = "0.1.6"
interrupt = { path = "../support/interrupt" }
lazy_static = "1.4.0"
log = "0.4"
rc_crypto = { path = "../support/rc_crypto", features = ["hawk"] } # XXX - does this fix benchmarks from failing?
serde = "1"
serde_json = "1"
serde_derive = "1"
sql-support = { path = "../support/sql" }
sync15 = { path = "../sync15" }
sync-guid = { path = "../support/guid", features = ["rusqlite_support", "random"] }
url = { version = "2.1.1", features = ["serde"] }

[dependencies.rusqlite]
version = "0.21.0"
features = ["functions", "bundled"]

[dev-dependencies]
env_logger = "0.7.0"
