[package]
name = "examples-fxa-client"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
edition = "2021"
publish = false

[dependencies]
nss = { path = "../../components/support/rc_crypto/nss" }
viaduct = { path = "../../components/viaduct"}
viaduct-hyper = { path = "../../components/support/viaduct-hyper" }
log = "0.4"
clap = {version = "4.2", default-features = false, features = ["std", "derive"]}
cli-support = { path = "../cli-support" }
fxa-client = { path = "../../components/fxa-client" }
anyhow = "1.0"
url = "2.2"
sync15 = { path = "../../components/sync15" }
