[package]
name = "fxaclient_ffi"
edition = "2018"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
license = "MPL-2.0"

[lib]
name = "fxaclient_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
ffi-support = { path = "../../support/ffi" }
log = "0.4.6"
lazy_static = "1.3.0"
viaduct = { path = "../../viaduct" }

[dependencies.fxa-client]
path = "../"

[features]
session_token = ["fxa-client/session_token"]
reqwest = ["viaduct/reqwest", "fxa-client/reqwest"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.7.0"
