[package]
name = "examples-suggest-cli"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"
publish = false

[dependencies]
cli-support = { path = "../cli-support" }
remote_settings = { path = "../../components/remote_settings" }
viaduct-reqwest = { path = "../../components/support/viaduct-reqwest" }
log = "0.4"
clap = {version = "4.2", features = ["derive"]}
suggest = { path = "../../components/suggest" }
anyhow = "1.0"
env_logger = { version = "0.10", default-features = false, features = ["humantime"] }
