[package]
name = "merino"
version = "0.1.0"
edition = "2021"
exclude = ["/android"]

[dependencies]
uniffi = { version = "0.31" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
viaduct = { path = "../viaduct" }
error-support = { path = "../support/error" }
thiserror = "2"

[build-dependencies]
uniffi = { version = "0.31", features = ["build"] }
