[package]
name = "merino"
version = "0.1.0"
edition = "2021"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
viaduct = { path = "../viaduct" }
error-support = { path = "../support/error" }
thiserror = "2"

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666", features = ["build"] }
