[package]
name = "init_rust_components"
version = "0.1.0"
edition = "2021"
authors = ["Johannes Schmidt <joschmidt@mozilla.com>"]
license = "MPL-2.0"
exclude = ["/android"]

[features]
default = []
keydb = ["nss/keydb"]
ohttp = ["dep:viaduct", "viaduct/ohttp"]

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
nss = { path = "../support/rc_crypto/nss" }
viaduct = { path = "../viaduct", optional = true }
