[package]
name = "megazord_focus"
edition = "2021"
version = "0.1.0"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
rust-log-forwarder = { path = "../../../components/support/rust-log-forwarder" }
viaduct = { path = "../../../components/viaduct" }
viaduct-reqwest = { path = "../../../components/support/viaduct-reqwest" }
nimbus-sdk = { path = "../../../components/nimbus" }
error-support = { path = "../../../components/support/error" }
remote_settings = { path = "../../../components/remote_settings" }
ads-client = { path = "../../../components/ads-client" }
