[package]
name = "nimbus-cli"
version = "0.5.0"
edition = "2021"
authors = ["Nimbus SDK Engineering"]
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["server"]
server = ["dep:axum", "dep:tokio", "dep:tower", "dep:tower-http", "dep:tower-livereload", "dep:hyper", "dep:local-ip-address"]

[dependencies]
clap = {version = "4.2", default-features = false, features = ["std", "derive", "error-context"]}
anyhow = "1.0.44"
remote_settings = { path = "../../remote_settings" }
nimbus-fml = { path = "../nimbus-fml", features = ["client-lib"] }
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
unicode-segmentation = "1.8.0"
viaduct = { path = "../../viaduct" }
viaduct-hyper = { path = "../../support/viaduct-hyper" }
glob = "0.3.1"
heck = "0.4.1"
whoami = "1.4.0"
update-informer = { version = "1.0.0", default-features = false }
serde_yaml = "0.9.21"
percent-encoding = "2.3.0"
copypasta = "0.8.2"
chrono = "0.4.26"
axum = { version = "0.6.18", optional = true }
tokio = { version = "1.29.1", optional = true, features = ["sync", "rt", "macros", "rt-multi-thread"] }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4.1", optional = true, features = ["fs", "set-header"] }
tower-livereload = { version = "0.8.0", optional = true }
hyper = { version = "0.14.27", optional = true, features = ["server"] }
local-ip-address = { version = "0.5.4", optional = true }
cfg-if = "1.0.0"
termcolor = "1.4.1"
