[package]
name = "loginsapi_ffi"
version = "0.1.0"
authors = ["Mark Hammond <mhammond@skippinet.com.au>"]

[lib]
name = "loginsapi_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
serde_json = "1.0"
failure = "0.1.1"
log = "0.4"
url = "1.6.0"
reqwest = "0.8.2"

[dependencies.ffi-toolkit]
#path="../../../../ffi-toolkit"
git = "https://github.com/mozilla/ffi-toolkit.git"
branch = "master"

[dependencies.sync15-adapter]
path = "../../../sync15-adapter"

[dependencies.sync15_passwords]
path = ".."

[dependencies.mentat]
git = "https://github.com/mozilla/mentat"
tag = "v0.8.1"
features = ["sqlcipher"]
default_features = false
