[package]
name = "loginsql_ffi"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[lib]
name = "logins_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
sqlcipher = ["logins-sql/sqlcipher", "rusqlite/sqlcipher"]
default = []

[dependencies]
serde_json = "1.0.28"
log = "0.4.5"
url = "1.7.1"

[dependencies.rusqlite]
version = "0.14.0"
features = []

[dependencies.logins-sql]
path = ".."
features = ["ffi"]

[dependencies.sync15-adapter]
path = "../../sync15-adapter"

[dependencies.ffi-support]
path = "../../components/support/ffi"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.6.0"
