[package]
name = "cli-support"
edition = "2018"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>", "Mark Hammond <mhammond@mozilla.com>"]
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
fxa-client = { path = "../../components/fxa-client" }
log = "0.4"
sync15 = { path = "../../components/sync15" }
url = "2.1"
webbrowser = "0.5"
# disable regex feature, as it's very costly for compile time and very rarely
# used.
[dependencies.env_logger]
version = "0.7"
default-features = false
features = ["termcolor", "atty", "humantime"]
