[package]
name = "cli-support"
edition = "2021"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>", "Mark Hammond <mhammond@mozilla.com>"]
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
fxa-client = { path = "../../components/fxa-client" }
remote_settings = { path = "../../components/remote_settings" }
sync_manager = { path = "../../components/sync_manager" }
tracing-support = { path = "../../components/support/tracing" }
log = "0.4"
sync15 = { path = "../../components/sync15", features=["sync-client"] }
url = "2"
open = "5"
dialoguer = { version = "0.11", default-features = false, features = ["password"] }
# disable regex feature, as it's very costly for compile time and very rarely
# used.
