[package]
name = "crashtest"
edition = "2018"
version = "0.1.0"
authors = ["Ryan Kelly <rfkelly@mozilla.com>"]
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
log = "0.4"
thiserror = "1.0"
uniffi = "^0.11"
uniffi_macros = "^0.11"

[build-dependencies]
uniffi_build = { version = "^0.11", features=["builtin-bindgen"] }
