[package]
name = "rust-log-forwarder"
version = "0.1.0"
edition = "2021"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
error-support = { path = "../error", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std"] }
tracing-support = { path = "../tracing" }

[dev-dependencies]
tracing = "0.1"

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666", features=["build"]}
