[package]
name = "embedded-uniffi-bindgen"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
uniffi_bindgen = "^0.14"
