[package]
name = "embedded-uniffi-bindgen"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"

[[bin]]
name = "embedded-uniffi-bindgen"

[dependencies]
anyhow = "1"
camino = "1"
glob = "0.3"
toml = "0.5"
clap = {version = "4.2", default-features = false, features = ["std", "derive"]}
serde = { version = "1", features = ["derive"] }
uniffi_bindgen = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
uniffi_pipeline = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
