[package]
name = "sync15_passwords"
version = "0.0.1"

[lib]
name = "sync15_passwords"
path = "src/lib.rs"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4"

serde = "^1.0.63"
serde_derive = "^1.0.63"
serde_json = "1.0"

[dev-dependencies]
env_logger = "0.5"
prettytable-rs = "0.6"
url = "1.6.0"

[dependencies.sync15-adapter]
path = "../../sync15-adapter"

[dependencies.mentat]
git = "https://github.com/mozilla/mentat"
tag = "v0.8.1"
features = ["sqlcipher"]
default_features = false

[dependencies.logins]
path = "../../logins"
# features = ["sqlcipher"]
# default_features = false
