[package]
name = "storage"
version = "0.1.0"
authors = ["Phil Jenvey <pjenvey@underboss.org>", "jrconlin <me+crypt@jrconlin.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
crypto = { path = "../crypto" }
lazy_static = "1.2"
log = "0.4"
failure = "0.1.5"
failure_derive = "0.1.5"
openssl = "0.10"
push-errors = { path = "../error" }
rusqlite = "0.16.0"
serde = { version = "1.0.85", features = ["derive"] }
serde_json = "1.0.37"
sql-support = { path = "../../support/sql" }

[dev-dependencies]
env_logger = "0.5.13"
