[package]
name = "megazord_ios"
edition = "2021"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]
license = "MPL-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
fxa-client = { path = "../../../components/fxa-client" }
logins = { path = "../../../components/logins" }
places = { path = "../../../components/places" }
rc_log_ffi = { path = "../../../components/rc_log" }
viaduct = { path = "../../../components/viaduct" }
viaduct-reqwest = { path = "../../../components/support/viaduct-reqwest" }
glean-ffi = { path = "../../../components/external/glean/glean-core/ffi" }
crashtest = { path = "../../../components/crashtest" }
nimbus-sdk = { path = "../../../components/nimbus" }
