[alias]
regen-protobufs = ["run", "--bin", "protobuf-gen", "tools/protobuf_files.toml"]
uniffi-bindgen = ["run", "--package", "embedded-uniffi-bindgen", "--"]
uniffi-bindgen-library-mode = ["run", "--package", "uniffi-bindgen-library-mode", "--"]
dev-install = ["install", "asdev"]
verify_env = ["asdev", "verify_env"]
fxa = ["run", "-p", "examples-fxa-client", "--"]
suggest-bench = ["bench", "-p", "suggest", "--features", "benchmark_api"]
suggest-debug-ingestion-sizes = ["run", "-p", "suggest", "--bin", "debug_ingestion_sizes", "--features", "benchmark_api"]
relevancy = ["run", "-p", "examples-relevancy-cli", "--"]
suggest = ["run", "-p", "examples-suggest-cli", "--"]
remote-settings = ["run", "-p", "examples-remote-settings-cli", "--"]
example = ["run", "-p", "examples-example-cli", "--"]
start-bindings = ["run", "-p", "start-bindings", "--"]
