[package]
name = "types"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

[dependencies.rusqlite]
version = "0.28.0"
features = ["functions", "bundled"]
