[package]
name = "places-ffi"
edition = "2018"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[lib]
name = "places_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
serde_json = "1.0.28"
log = "0.4"
url = "1.7.1"
ffi-support = { path = "../../support/ffi" }

[dependencies.rusqlite]
version = "0.16.0"
features = ["sqlcipher", "limits", "functions"]

[dependencies.sync15]
path = "../../sync15"

[dependencies.places]
path = ".."
features = ["ffi"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.7.0"
