[package]
name = "places-ffi"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[lib]
name = "places_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
sqlcipher = ["places/sqlcipher", "rusqlite/sqlcipher"]
default = []

[dependencies]
serde_json = "1.0.28"
log = "0.4.5"
url = "1.7.1"
ffi-support = { path = "../../support/ffi" }

[dependencies.rusqlite]
version = "0.14.0"
features = ["limits", "functions"]

[dependencies.sync15-adapter]
path = "../../../sync15-adapter"

[dependencies.places]
path = ".."
features = ["ffi"]

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.6.0"
