[package]
name = "search"
version = "0.1.0"
edition = "2021"
description = "Library for search service related components."
readme = "README.md"
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
error-support = { path = "../support/error" }
parking_lot = ">=0.11,<=0.12"
remote_settings = { path = "../remote_settings" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
uniffi = { version = "0.31" }
firefox-versioning = { path = "../support/firefox-versioning" }

[build-dependencies]
uniffi = { version = "0.31", features = ["build"] }

[dev-dependencies]
error-support = { path = "../support/error", features = ["testing"] }
once_cell = "1.18.0"
mockito = { version = "0.31", default-features = false}
viaduct-dev = { path = "../support/viaduct-dev"}
