[bindings.kotlin]
package_name = "mozilla.appservices.push"
omit_checksums = true

[bindings.swift]
ffi_module_name = "MozillaRustComponents"
ffi_module_filename = "pushFFI"
generate_module_map = false
