[package]
name = "merino-cli"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"
publish = false


[dependencies]
clap = {version = "4.2", default-features = false, features = ["std", "derive"]}
anyhow = "1.0"
serde_json = "1.0"
merino = { path = "../../components/merino" }
viaduct = { path = "../../components/viaduct"}
viaduct-hyper = { path = "../../components/support/viaduct-hyper" }
