[package]
name = "megazord"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
fxa-client = { path = "../../components/fxa-client" }
logins = { path = "../../components/logins" }
places-ffi = { path = "../../components/places/ffi" }
push-ffi = { path = "../../components/push/ffi" }
rc_log_ffi = { path = "../../components/rc_log" }
viaduct = { path = "../../components/viaduct" }
sync_manager_ffi = { path = "../../components/sync_manager/ffi" }
nimbus-sdk = { path = "../../components/nimbus" }
autofill = { path = "../../components/autofill" }
crashtest = { path = "../../components/crashtest" }

lazy_static = "1.4"
