[package]
name = "megazord"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
fxa-client = { path = "../../components/fxa-client" }
logins = { path = "../../components/logins" }
tabs = { path = "../../components/tabs/", features = ["full-sync"] }
sync_manager = { path = "../../components/sync_manager/" }
places = { path = "../../components/places" }
push = { path = "../../components/push" }
rc_log_ffi = { path = "../../components/rc_log" }
rust-log-forwarder = { path = "../../components/support/rust-log-forwarder" }
viaduct = { path = "../../components/viaduct" }
nimbus-sdk = { path = "../../components/nimbus-sdk" }
autofill = { path = "../../components/autofill" }
crashtest = { path = "../../components/crashtest" }
error-support = { path = "../../components/support/error" }

lazy_static = "1.4"
