[package]
name = "communications"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>", "Phil Jenvey <pjenvey@underboss.org>"]
edition = "2018"

[dependencies]
hex = "0.3"
http = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9"

storage = {path="../storage"}
push-errors = {path="../error"}
crypto = {path="../crypto"}
config = {path="../config"}

[dev-dependencies]
mockito = "0.15"
