[package]
name = "support_fetch"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
url = "1.7.2"
log = "0.4"
lazy_static = "1.3.0"
serde = "1.0"
serde_json = "1.0"
prost = "0.5.0"
prost-derive = "0.5.0"
bytes = "0.4.12"

[target.'cfg(not(target_os="android"))'.dependencies]
reqwest = "0.9.11"


[build-dependencies]
prost-build = "0.5.0"
