[package]
name = "reference-browser"
edition = "2018"
version = "0.1.0"
authors = ["application-services <application-services@mozilla.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
fxaclient_ffi = { path = "../../components/fxa-client/ffi" }
logins_ffi = { path = "../../components/logins/ffi" }
places-ffi = { path = "../../components/places/ffi" }
ac_log = { path = "../../components/ac_log" }
