[package]
name = "fxa-client-ffi"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]

[lib]
name = "fxa_client"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
libc = "0.2"

[dependencies.fxa-client]
path = "../"

[features]
browserid = ["fxa-client/browserid"]
