[package]
name = "example-sync-pass"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
edition = "2021"
publish = false

[[example]]
name = "sync-pass"
path = "src/sync-pass.rs"

[dev-dependencies]
base64 = "0.21"
logins = { path = "../../components/logins" }
sync15 = { path = "../../components/sync15" }
sync-guid = { path = "../../components/support/guid" }
log = "0.4"
sql-support = { path = "../../components/support/sql" }
anyhow = "1.0"
prettytable-rs = "0.10"
fxa-client = { path = "../../components/fxa-client" }
chrono = "0.4"
clap = "4"
cli-support = { path = "../cli-support" }
tempfile = "3"
serde_json = "1.0"
url = "2.2"
viaduct-reqwest = { path = "../../components/support/viaduct-reqwest" }
rusqlite = { version = "0.33.0", features = ["limits"] }
