[package]
name = "suggest"
version = "0.1.0"
edition = "2021"
description = "Manages sponsored and web suggestions for Firefox Suggest"
readme = "README.md"
license = "MPL-2.0"
exclude = ["/android"]

[dependencies]
anyhow = "1.0"
interrupt-support = { path = "../support/interrupt" }
once_cell = "1.5"
parking_lot = ">=0.11,<=0.12"
remote_settings = { path = "../remote_settings" }
rusqlite = { version = "0.29.0", features = ["functions", "bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sql-support = { path = "../support/sql" }
thiserror = "1"
uniffi = "0.24.1"

[dev-dependencies]
env_logger = { version = "0.7", default-features = false }
expect-test = "1.4"

[build-dependencies]
uniffi = { version = "0.24.1", features = ["build"] }
