[package]
name = "suggest"
version = "0.1.0"
edition = "2021"
description = "Manages sponsored and web suggestions for Firefox Suggest"
readme = "README.md"
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
anyhow = "1.0"
rmp-serde = "1.3"
chrono = "0.4"
extend = "1.1"
interrupt-support = { path = "../support/interrupt" }
log = "0.4"
once_cell = "1.5"
parking_lot = ">=0.11,<=0.12"
remote_settings = { path = "../remote_settings" }
rusqlite = { version = "0.33.0", features = ["functions", "bundled", "load_extension"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
error-support = { path = "../support/error" }
sql-support = { path = "../support/sql" }
viaduct = { path = "../viaduct" }
viaduct-reqwest = { path = "../support/viaduct-reqwest", optional=true }
tempfile = { version = "3.2.0", optional = true }
thiserror = "1"
uniffi = { version = "0.28.2" }
url = { version = "2.1", features = ["serde"] }

[dev-dependencies]
criterion = "0.5"
env_logger = { version = "0.10", default-features = false }
expect-test = "1.4"
hex = "0.4"
rc_crypto = { path = "../support/rc_crypto" }

[build-dependencies]
uniffi = { version = "0.28.2", features = ["build"] }

[features]
# Required for the benchmarks to work, wasted bytes otherwise.
benchmark_api = ["tempfile", "viaduct-reqwest"]

[lib]
bench = false

[[bench]]
name = "benchmark_all"
harness = false
required-features = ["benchmark_api"]

[[bin]]
name = "debug_ingestion_sizes"
required-features = ["benchmark_api"]
bench = false
