[package]
name = "suggest"
version = "0.1.0"
edition = "2021"
description = "Manages sponsored and web suggestions for Firefox Suggest"
readme = "README.md"
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
extend = "1.1"
icu_casemap = "2"
# Turn off the default features for icu_normalizer to allow it to be compiled in parallel
# with icu_properties.
icu_normalizer = { version = "2", default-features = false, features = ["compiled_data"] }
icu_properties = "2"
interrupt-support = { path = "../support/interrupt" }
once_cell = "1.5"
parking_lot = ">=0.11,<=0.12"
remote_settings = { path = "../remote_settings" }
rusqlite = { version = "0.37.0", features = ["functions", "bundled", "load_extension", "collation"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
error-support = { path = "../support/error" }
sql-support = { path = "../support/sql" }
viaduct = { path = "../viaduct" }
tempfile = { version = "3.2.0", optional = true }
thiserror = "2"
uniffi = { version = "0.31" }
url = { version = "2.1", features = ["serde"] }

[dev-dependencies]
error-support = { path = "../support/error", features = ["testing"] }
expect-test = "1.4"
hex = "0.4"
itertools = "0.14"
rc_crypto = { path = "../support/rc_crypto" }

[build-dependencies]
uniffi = { version = "0.31", features = ["build"] }

[features]
# Required for the benchmarks to work, wasted bytes otherwise.
benchmark_api = ["tempfile"]
