# In this file, every section corresponds to a protobuf file to compile.
# `dir` refers to the directory where the protobuf file can be found, relative to this file location.
# (Optional) `out_dir` refers to where the compiled rust file should be saved. If not present `dir` is used.

["fxa_msg_types.proto"]
dir = "../components/fxa-client/src/"

["logins_msg_types.proto"]
dir = "../components/logins/src/"

["places_msg_types.proto"]
dir = "../components/places/src/"

["push_msg_types.proto"]
dir = "../components/push/src/"

["manager_msg_types.proto"]
dir = "../components/sync_manager/src/"

["tabs_msg_types.proto"]
dir = "../components/tabs/src/"

["fetch_msg_types.proto"]
dir = "../components/viaduct/src/"
