[package]
name = "uniffi-bindgen-library-mode"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
uniffi = { version = "0.29.0", features = ["cli"] }
uniffi_bindgen = { version = "0.29.0" }
clap = "4"
cargo_metadata = "0.15"
camino = "1"
anyhow = "1"
