[package]
name = "uniffi-bindgen-library-mode"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666", features = ["cli"] }
uniffi_bindgen = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }
clap = {version = "4.2", default-features = false, features = ["std", "derive"]}
cargo_metadata = "0.19"
camino = "1"
anyhow = "1"
