[package]
name = "interrupt-support"
version = "0.1.0"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
parking_lot = ">=0.11,<=0.12"
rusqlite = { version = "0.37.0", features = ["functions", "limits", "bundled", "unlock_notify"] }
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666" }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", rev = "106e12ae2a0474a1880667ed3a4b050fcf1c6666", features = ["build"] }
