[package]
name = "interrupt-support"
version = "0.1.0"
authors = ["Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
parking_lot = ">=0.11,<=0.12"
rusqlite = { version = "0.33.0", features = ["functions", "limits", "bundled", "unlock_notify"] }
uniffi = { version = "0.28.2" }

[build-dependencies]
uniffi = { version = "0.28.2", features = ["build"] }
